[package]
name = "my_library"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fuzzy-matcher = "0.3.7"
# reqwestの導入
reqwest = { features = ["blocking"], version = "0.12.2"}
scraper = "0.19.0"